version: "2"
run:
  concurrency: 4
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 200
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G402
        - G106
    lll:
      line-length: 120
    loggercheck:
      kitlog: false
      klog: false
      logr: false
      zap: false
    nlreturn:
      block-size: 4
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
